import { NextResponse } from 'next/server'
import { supabaseAdmin } from '@/lib/supabaseAdmin'
import { randomUUID } from 'crypto'

// New companies to add
const newCompanies = [
  {
    id: 'c0000000-0000-4000-8000-000000000031',
    name: 'TIAA',
    website: 'https://www.tiaa.org',
    careers_url: 'https://careers.tiaa.org',
    description: 'Fortune 100 financial services organization providing retirement solutions, investment management, and banking for people in academic, research, medical, cultural, and governmental fields.',
  },
  {
    id: 'c0000000-0000-4000-8000-000000000032',
    name: 'Northwestern Mutual',
    website: 'https://www.northwesternmutual.com',
    careers_url: 'https://careers.northwesternmutual.com',
    description: 'Financial services company offering life insurance, long-term care insurance, disability income insurance, annuities, and investment products.',
  },
  {
    id: 'c0000000-0000-4000-8000-000000000033',
    name: 'TD Securities',
    website: 'https://www.tdsecurities.com',
    careers_url: 'https://jobs.td.com',
    description: 'Global investment bank offering capital markets, advisory, and trading services. Part of TD Bank Group, one of the largest banks in North America.',
  },
  {
    id: 'c0000000-0000-4000-8000-000000000034',
    name: 'Prudential Financial',
    website: 'https://www.prudential.com',
    careers_url: 'https://jobs.prudential.com',
    description: 'Global financial services leader offering insurance, retirement planning, investment management, and other products and services.',
  },
  {
    id: 'c0000000-0000-4000-8000-000000000035',
    name: 'Barclays',
    website: 'https://www.barclays.com',
    careers_url: 'https://joinus.barclays.com',
    description: 'British multinational investment bank and financial services company with a strong presence in investment banking, wealth management, and consumer banking.',
  },
]

// New jobs for both new and existing companies
const newJobs = [
  // ── EY (new listings based on real career page data) ──
  {
    company_id: 'a1b2c3d4-0008-4000-8000-000000000008',
    title: 'Assurance Audit Intern - Summer 2027',
    category: 'Accounting',
    location: 'Multiple US Locations',
    remote_type: 'Hybrid',
    salary_min: null,
    salary_max: null,
    job_type: 'Internship',
    pipeline_stage: 'Junior Internship',
    description: 'Join EY\'s Assurance practice as a Summer 2027 intern. Work alongside audit professionals serving Fortune 500 clients across diverse industries. Gain hands-on experience with audit methodology, data analytics, and financial reporting. Develop skills in risk assessment, internal controls testing, and substantive audit procedures while building a professional network.',
    apply_url: 'https://usearlycareers.ey.com/search-jobs',
    source_url: 'https://usearlycareers.ey.com/search-jobs',
    licenses_required: ['CPA Track'],
    licenses_info: { study_time_days: null, pass_deadline_days: null, max_attempts: null, prep_materials_paid: true, notes: 'CPA eligibility preferred; 150 credit hours recommended by start date' },
  },
  {
    company_id: 'a1b2c3d4-0008-4000-8000-000000000008',
    title: 'EY-Parthenon Financial Diligence Summer Associate 2027',
    category: 'Consulting',
    location: 'New York, NY / Chicago, IL / Boston, MA',
    remote_type: 'On-site',
    salary_min: 95000,
    salary_max: 110000,
    job_type: 'Internship',
    pipeline_stage: 'Senior Internship',
    description: 'EY-Parthenon\'s Financial Diligence team provides buy-side and sell-side financial due diligence for private equity and corporate clients. As a Summer Associate, you\'ll analyze financial data, build quality of earnings analyses, and present findings to deal teams. Strong foundation for a career in transaction advisory, private equity, or corporate development.',
    apply_url: 'https://usearlycareers.ey.com/search-jobs',
    source_url: 'https://usearlycareers.ey.com/search-jobs',
    licenses_required: ['None Required'],
    licenses_info: null,
  },
  {
    company_id: 'a1b2c3d4-0008-4000-8000-000000000008',
    title: 'Service Delivery Center Associate Analyst - Assurance',
    category: 'Accounting',
    location: 'San Antonio, TX',
    remote_type: 'On-site',
    salary_min: 52000,
    salary_max: 62000,
    job_type: 'Full-time',
    pipeline_stage: 'No Experience Required',
    description: 'Join EY\'s Global Delivery Services team supporting audit engagements from the San Antonio Service Delivery Center. Perform data extraction, analytical procedures, and audit support tasks using EY\'s proprietary technology platforms. Great entry point into public accounting with structured training and CPA support.',
    apply_url: 'https://usearlycareers.ey.com/search-jobs',
    source_url: 'https://usearlycareers.ey.com/search-jobs',
    licenses_required: ['CPA Track'],
    licenses_info: { study_time_days: 180, pass_deadline_days: 365, max_attempts: null, prep_materials_paid: true, notes: 'CPA study materials provided; firm sponsors exam fees' },
  },
  {
    company_id: 'a1b2c3d4-0008-4000-8000-000000000008',
    title: 'Tax Diversified Staff - 360 Careers',
    category: 'Accounting',
    location: 'Multiple US Locations',
    remote_type: 'Hybrid',
    salary_min: 62000,
    salary_max: 75000,
    job_type: 'Full-time',
    pipeline_stage: 'New Grad',
    description: 'EY\'s 360 Careers program is designed for candidates with non-traditional backgrounds entering Tax. Work on federal and state tax compliance, provision calculations, and tax planning for corporate clients. Comprehensive training program with mentorship, study support, and accelerated career development.',
    apply_url: 'https://usearlycareers.ey.com/search-jobs',
    source_url: 'https://usearlycareers.ey.com/search-jobs',
    licenses_required: ['CPA Track'],
    licenses_info: { study_time_days: 180, pass_deadline_days: 540, max_attempts: null, prep_materials_paid: true, notes: 'Firm covers CPA exam costs and provides Becker study materials' },
  },
  {
    company_id: 'a1b2c3d4-0008-4000-8000-000000000008',
    title: 'Consulting - People Consulting Associate Analyst (Actuarial)',
    category: 'Insurance',
    location: 'Dallas, TX',
    remote_type: 'Hybrid',
    salary_min: 65000,
    salary_max: 80000,
    job_type: 'Full-time',
    pipeline_stage: 'New Grad',
    description: 'Support actuarial consulting engagements for insurance company clients. Perform actuarial analyses, build pricing models, and assist with reserve calculations. Ideal for candidates pursuing actuarial credentials who want consulting exposure across P&C and life insurance lines of business.',
    apply_url: 'https://usearlycareers.ey.com/search-jobs',
    source_url: 'https://usearlycareers.ey.com/search-jobs',
    licenses_required: ['None Required'],
    licenses_info: null,
  },

  // ── Vanguard (based on real career page data) ──
  {
    company_id: 'c0000000-0000-4000-8000-000000000023',
    title: 'Client Relationship Associate',
    category: 'Private Wealth',
    location: 'Charlotte, NC',
    remote_type: 'Hybrid',
    salary_min: 52000,
    salary_max: 65000,
    job_type: 'Full-time',
    pipeline_stage: 'Early Career',
    description: 'Support Vanguard\'s high-net-worth client relationships by providing comprehensive investment guidance and financial planning support. Handle client inquiries, process transactions, and collaborate with senior advisors on portfolio reviews. Obtain Series 7 and 66 licenses within 120 days of start.',
    apply_url: 'https://www.vanguardjobs.com/job-search-results/',
    source_url: 'https://www.vanguardjobs.com/job-search-results/',
    licenses_required: ['SIE', 'Series 7', 'Series 66'],
    licenses_info: { study_time_days: 120, pass_deadline_days: 180, max_attempts: 3, prep_materials_paid: true, notes: 'Vanguard provides paid study time and covers all exam fees' },
  },
  {
    company_id: 'c0000000-0000-4000-8000-000000000023',
    title: 'Client Service Excellence Representative (FINRA Licensed)',
    category: 'Financial Planning',
    location: 'Columbus, OH (Remote)',
    remote_type: 'Remote',
    salary_min: 48000,
    salary_max: 58000,
    job_type: 'Full-time',
    pipeline_stage: 'Early Career',
    description: 'Deliver exceptional service to Vanguard investors by providing licensed financial guidance over the phone. Educate clients on investment products, retirement planning, and portfolio strategies. Must hold or obtain FINRA SIE, Series 7, and Series 63 licenses. Work-from-home position with full training program.',
    apply_url: 'https://www.vanguardjobs.com/job-search-results/',
    source_url: 'https://www.vanguardjobs.com/job-search-results/',
    licenses_required: ['SIE', 'Series 7', 'Series 63'],
    licenses_info: { study_time_days: 90, pass_deadline_days: 150, max_attempts: 3, prep_materials_paid: true, notes: 'Paid training period; Vanguard covers all licensing costs' },
  },

  // ── Fidelity ──
  {
    company_id: 'c0000000-0000-4000-8000-000000000021',
    title: 'Financial Representative',
    category: 'Financial Planning',
    location: 'Multiple US Locations',
    remote_type: 'Hybrid',
    salary_min: 50000,
    salary_max: 65000,
    job_type: 'Full-time',
    pipeline_stage: 'No Experience Required',
    description: 'Help Fidelity clients navigate their financial journey as a licensed Financial Representative. Provide guidance on retirement accounts, brokerage services, and investment planning. Comprehensive paid training program with licensing support. No finance background required; Fidelity invests in your development from day one.',
    apply_url: 'https://jobs.fidelity.com/en/students/career-discovery-programs/',
    source_url: 'https://jobs.fidelity.com/en/students/career-discovery-programs/',
    licenses_required: ['SIE', 'Series 7', 'Series 63'],
    licenses_info: { study_time_days: 90, pass_deadline_days: 150, max_attempts: 3, prep_materials_paid: true, notes: 'Fidelity covers all exam fees and provides dedicated study time' },
  },
  {
    company_id: 'c0000000-0000-4000-8000-000000000021',
    title: 'Equity Research Associate - Summer 2027',
    category: 'Research',
    location: 'Boston, MA',
    remote_type: 'On-site',
    salary_min: null,
    salary_max: null,
    job_type: 'Internship',
    pipeline_stage: 'Junior Internship',
    description: 'Join Fidelity\'s equity research team for a 10-week summer program. Conduct fundamental analysis on public equities, build financial models, and present investment recommendations to portfolio managers. Work alongside experienced analysts covering specific sectors. Strong path to full-time research analyst role.',
    apply_url: 'https://jobs.fidelity.com/en/students/career-discovery-programs/',
    source_url: 'https://jobs.fidelity.com/en/students/career-discovery-programs/',
    licenses_required: ['None Required'],
    licenses_info: null,
  },

  // ── TIAA (new company) ──
  {
    company_id: 'c0000000-0000-4000-8000-000000000031',
    title: 'Wealth Management Associate',
    category: 'Financial Planning',
    location: 'Charlotte, NC / New York, NY',
    remote_type: 'Hybrid',
    salary_min: 58000,
    salary_max: 72000,
    job_type: 'Full-time',
    pipeline_stage: 'New Grad',
    description: 'Help academic and nonprofit professionals plan for retirement as a TIAA Wealth Management Associate. Conduct client consultations, develop financial plans, and provide investment guidance. Obtain Series 7 and 66 licenses with full firm support. Structured 18-month development program with mentorship.',
    apply_url: 'https://careers.tiaa.org',
    source_url: 'https://careers.tiaa.org',
    licenses_required: ['SIE', 'Series 7', 'Series 66'],
    licenses_info: { study_time_days: 120, pass_deadline_days: 180, max_attempts: 3, prep_materials_paid: true, notes: 'TIAA sponsors all licensing exams and provides Kaplan study materials' },
  },
  {
    company_id: 'c0000000-0000-4000-8000-000000000031',
    title: 'Investment Analyst - Fixed Income',
    category: 'Research',
    location: 'New York, NY',
    remote_type: 'Hybrid',
    salary_min: 75000,
    salary_max: 90000,
    job_type: 'Full-time',
    pipeline_stage: 'New Grad',
    description: 'Join TIAA\'s fixed income investment team managing over $300 billion in assets. Perform credit analysis on corporate bonds and structured products, build financial models, and contribute to investment recommendations. Support portfolio managers with market research, relative value analysis, and trade execution.',
    apply_url: 'https://careers.tiaa.org',
    source_url: 'https://careers.tiaa.org',
    licenses_required: ['CFA Level 1'],
    licenses_info: { study_time_days: null, pass_deadline_days: null, max_attempts: null, prep_materials_paid: true, notes: 'CFA candidacy encouraged; firm reimburses exam fees upon passing' },
  },

  // ── Northwestern Mutual (new company) ──
  {
    company_id: 'c0000000-0000-4000-8000-000000000032',
    title: 'Financial Advisor - College Financial Representatives Program',
    category: 'Financial Planning',
    location: 'Multiple US Locations',
    remote_type: 'On-site',
    salary_min: null,
    salary_max: null,
    job_type: 'Internship',
    pipeline_stage: 'Junior Internship',
    description: 'Northwestern Mutual\'s College Financial Representatives program is one of the top-rated internships in finance. Gain real-world experience in financial planning, insurance, and wealth management while earning commissions. Build a client base, develop business skills, and explore a career path in financial services. Open to all majors.',
    apply_url: 'https://careers.northwesternmutual.com',
    source_url: 'https://careers.northwesternmutual.com',
    licenses_required: ['None Required'],
    licenses_info: null,
  },
  {
    company_id: 'c0000000-0000-4000-8000-000000000032',
    title: 'Financial Advisor',
    category: 'Financial Planning',
    location: 'Multiple US Locations',
    remote_type: 'On-site',
    salary_min: null,
    salary_max: null,
    job_type: 'Full-time',
    pipeline_stage: 'No Experience Required',
    description: 'Launch your career as a Financial Advisor with Northwestern Mutual. Build and manage a client practice focused on financial planning, retirement, insurance, and investments. Comprehensive training program with mentorship from established advisors. Commission-based compensation with unlimited earning potential.',
    apply_url: 'https://careers.northwesternmutual.com',
    source_url: 'https://careers.northwesternmutual.com',
    licenses_required: ['SIE', 'Series 7', 'Series 63'],
    licenses_info: { study_time_days: 60, pass_deadline_days: 120, max_attempts: 3, prep_materials_paid: true, notes: 'Licensing support and paid study time provided during onboarding' },
  },

  // ── TD Securities (new company) ──
  {
    company_id: 'c0000000-0000-4000-8000-000000000033',
    title: '2026 Investment Banking Summer Analyst',
    category: 'Investment Banking',
    location: 'New York, NY',
    remote_type: 'On-site',
    salary_min: 95000,
    salary_max: 110000,
    job_type: 'Internship',
    pipeline_stage: 'Junior Internship',
    description: 'Join TD Securities\' Investment Banking division for a 10-week summer program in New York. Work on live M&A, equity, and debt transactions across industry verticals including healthcare, technology, industrials, and financial institutions. Build financial models, conduct due diligence, and prepare client presentations.',
    apply_url: 'https://jobs.td.com',
    source_url: 'https://jobs.td.com',
    licenses_required: ['None Required'],
    licenses_info: null,
    grad_date_required: true,
    grad_date_earliest: '2026-12-01',
    grad_date_latest: '2027-06-30',
  },
  {
    company_id: 'c0000000-0000-4000-8000-000000000033',
    title: 'Fixed Income Sales & Trading Analyst',
    category: 'Sales & Trading',
    location: 'New York, NY',
    remote_type: 'On-site',
    salary_min: 85000,
    salary_max: 100000,
    job_type: 'Full-time',
    pipeline_stage: 'New Grad',
    description: 'Join TD Securities\' Fixed Income trading desk as a new analyst. Rotate across rates, credit, and securitized products desks during a structured training program. Support traders with pricing, risk analysis, and client communication. Strong quantitative skills and market knowledge required.',
    apply_url: 'https://jobs.td.com',
    source_url: 'https://jobs.td.com',
    licenses_required: ['SIE', 'Series 7', 'Series 63'],
    licenses_info: { study_time_days: 90, pass_deadline_days: 150, max_attempts: 3, prep_materials_paid: true, notes: 'Licensing exams sponsored during training program' },
  },

  // ── Prudential (new company) ──
  {
    company_id: 'c0000000-0000-4000-8000-000000000034',
    title: 'Investment Management Analyst - PGIM',
    category: 'Research',
    location: 'Newark, NJ',
    remote_type: 'Hybrid',
    salary_min: 75000,
    salary_max: 90000,
    job_type: 'Full-time',
    pipeline_stage: 'New Grad',
    description: 'Join PGIM, Prudential\'s $1.3 trillion global investment management business, as an analyst. Support portfolio management teams with research, financial modeling, and investment analysis across fixed income, equities, or real estate. Structured rotational program with exposure to multiple asset classes.',
    apply_url: 'https://jobs.prudential.com',
    source_url: 'https://jobs.prudential.com',
    licenses_required: ['None Required'],
    licenses_info: null,
  },
  {
    company_id: 'c0000000-0000-4000-8000-000000000034',
    title: 'Actuarial Analyst - Individual Life Insurance',
    category: 'Insurance',
    location: 'Newark, NJ',
    remote_type: 'Hybrid',
    salary_min: 68000,
    salary_max: 82000,
    job_type: 'Full-time',
    pipeline_stage: 'New Grad',
    description: 'Join Prudential\'s actuarial team supporting individual life insurance product development and pricing. Build actuarial models, perform experience studies, and support regulatory filings. Prudential sponsors actuarial exam preparation with study time, materials, and exam fee reimbursement. Rotation opportunities across business lines.',
    apply_url: 'https://jobs.prudential.com',
    source_url: 'https://jobs.prudential.com',
    licenses_required: ['None Required'],
    licenses_info: null,
  },
  {
    company_id: 'c0000000-0000-4000-8000-000000000034',
    title: 'Financial Planning Associate',
    category: 'Financial Planning',
    location: 'Multiple US Locations',
    remote_type: 'On-site',
    salary_min: 55000,
    salary_max: 70000,
    job_type: 'Full-time',
    pipeline_stage: 'No Experience Required',
    description: 'Help clients achieve financial wellness as a Prudential Financial Planning Associate. Conduct financial needs analyses, recommend insurance and investment solutions, and build a client practice. Comprehensive training program with licensing support, mentorship, and a base salary during your first two years.',
    apply_url: 'https://jobs.prudential.com',
    source_url: 'https://jobs.prudential.com',
    licenses_required: ['SIE', 'Series 7', 'Series 66'],
    licenses_info: { study_time_days: 90, pass_deadline_days: 150, max_attempts: 3, prep_materials_paid: true, notes: 'Full licensing support with paid study time and exam fee coverage' },
  },

  // ── Barclays (new company) ──
  {
    company_id: 'c0000000-0000-4000-8000-000000000035',
    title: '2026 Investment Banking Analyst Program',
    category: 'Investment Banking',
    location: 'New York, NY',
    remote_type: 'On-site',
    salary_min: 110000,
    salary_max: 110000,
    job_type: 'Full-time',
    pipeline_stage: 'New Grad',
    description: 'Join Barclays\' Investment Banking Division as a full-time analyst. Work on M&A advisory, leveraged finance, and equity and debt capital markets transactions. Industry coverage spans healthcare, TMT, industrials, financial sponsors, and natural resources. Two-year analyst program with strong deal flow and client exposure.',
    apply_url: 'https://joinus.barclays.com',
    source_url: 'https://joinus.barclays.com',
    licenses_required: ['SIE', 'Series 79', 'Series 63'],
    licenses_info: { study_time_days: 90, pass_deadline_days: 180, max_attempts: 3, prep_materials_paid: true, notes: 'Barclays sponsors all required FINRA exams during training' },
    grad_date_required: true,
    grad_date_earliest: '2025-12-01',
    grad_date_latest: '2026-06-30',
  },
  {
    company_id: 'c0000000-0000-4000-8000-000000000035',
    title: 'Quantitative Analytics Summer Analyst 2027',
    category: 'Risk Management',
    location: 'New York, NY',
    remote_type: 'On-site',
    salary_min: null,
    salary_max: null,
    job_type: 'Internship',
    pipeline_stage: 'Junior Internship',
    description: 'Join Barclays\' Quantitative Analytics team for a 10-week summer program. Develop pricing models, validate risk models, and work with derivatives structuring teams. Ideal for students with strong backgrounds in mathematics, statistics, or computational finance. Exposure to interest rate, credit, and equity derivative products.',
    apply_url: 'https://joinus.barclays.com',
    source_url: 'https://joinus.barclays.com',
    licenses_required: ['None Required'],
    licenses_info: null,
    grad_date_required: true,
    grad_date_earliest: '2027-05-01',
    grad_date_latest: '2028-06-30',
  },

  // ── Bank of America (adding more roles) ──
  {
    company_id: '4419bea8-9bd5-4279-9aec-74edd04907eb',
    title: 'Global Markets Sales & Trading Analyst',
    category: 'Sales & Trading',
    location: 'New York, NY',
    remote_type: 'On-site',
    salary_min: 95000,
    salary_max: 110000,
    job_type: 'Full-time',
    pipeline_stage: 'New Grad',
    description: 'Join Bank of America\'s Global Markets division as a Sales & Trading analyst. Rotate across equities, fixed income, currencies, and commodities desks during a structured training program. Support traders and salespeople with market analysis, pricing, and risk management. Complete FINRA licensing during initial training.',
    apply_url: 'https://campus.bankofamerica.com/careers/Global-Banking-Markets-Analyst-Program-Full-Time.html',
    source_url: 'https://campus.bankofamerica.com/careers/',
    licenses_required: ['SIE', 'Series 7', 'Series 63'],
    licenses_info: { study_time_days: 90, pass_deadline_days: 150, max_attempts: 3, prep_materials_paid: true, notes: 'All licensing exams sponsored during initial training period' },
  },
  {
    company_id: '4419bea8-9bd5-4279-9aec-74edd04907eb',
    title: 'Merrill Lynch Financial Solutions Advisor',
    category: 'Private Wealth',
    location: 'Multiple US Locations',
    remote_type: 'On-site',
    salary_min: 55000,
    salary_max: 75000,
    job_type: 'Full-time',
    pipeline_stage: 'No Experience Required',
    description: 'Begin your wealth management career at Merrill Lynch as a Financial Solutions Advisor. Engage with clients to understand their financial goals, recommend banking and investment solutions, and develop relationships for long-term growth. Earn Series 7 and 66 licenses with full support. Clear career path to Financial Advisor role.',
    apply_url: 'https://campus.bankofamerica.com/careers/',
    source_url: 'https://campus.bankofamerica.com/careers/',
    licenses_required: ['SIE', 'Series 7', 'Series 66'],
    licenses_info: { study_time_days: 120, pass_deadline_days: 180, max_attempts: 3, prep_materials_paid: true, notes: 'Merrill covers all licensing costs and provides structured study program' },
  },

  // ── Citi (adding more roles) ──
  {
    company_id: '16054ab5-b9d4-4bae-bf53-20e9d59ef19a',
    title: 'Treasury & Trade Solutions (TTS) Analyst',
    category: 'Commercial Banking',
    location: 'New York, NY',
    remote_type: 'Hybrid',
    salary_min: 85000,
    salary_max: 100000,
    job_type: 'Full-time',
    pipeline_stage: 'New Grad',
    description: 'Join Citi\'s Treasury & Trade Solutions business as an analyst supporting corporate clients with cash management, payments, trade finance, and liquidity solutions. Work with multinational companies to optimize their treasury operations across 90+ countries. Strong analytical and client-facing role.',
    apply_url: 'https://jobs.citi.com/early-careers',
    source_url: 'https://jobs.citi.com/early-careers',
    licenses_required: ['None Required'],
    licenses_info: null,
  },

  // ── Wells Fargo ──
  {
    company_id: '21ed5186-8cbe-4ba5-ae99-dadf8104f905',
    title: 'Commercial Banking Associate Program',
    category: 'Commercial Banking',
    location: 'Charlotte, NC / San Francisco, CA',
    remote_type: 'Hybrid',
    salary_min: 75000,
    salary_max: 90000,
    job_type: 'Full-time',
    pipeline_stage: 'New Grad',
    description: 'Wells Fargo\'s Commercial Banking Associate Program is a structured entry into relationship management for middle market companies. Learn credit analysis, loan structuring, and client relationship management during a multi-year program with rotations across industry verticals and product groups.',
    apply_url: 'https://www.wellsfargojobs.com/en/early-careers/',
    source_url: 'https://www.wellsfargojobs.com/en/early-careers/',
    licenses_required: ['None Required'],
    licenses_info: null,
  },

  // ── Goldman Sachs ──
  {
    company_id: 'a1b2c3d4-0001-4000-8000-000000000001',
    title: 'Operations Analyst Program',
    category: 'Operations',
    location: 'Salt Lake City, UT / Dallas, TX',
    remote_type: 'Hybrid',
    salary_min: 70000,
    salary_max: 85000,
    job_type: 'Full-time',
    pipeline_stage: 'New Grad',
    description: 'Goldman Sachs Operations is the backbone of every transaction. As an analyst, you\'ll work on trade confirmation, settlement, and risk management processes across global markets. The program offers rotations through different desks and exposure to technology, process improvement, and regulatory compliance.',
    apply_url: 'https://www.goldmansachs.com/careers/students/programs-and-internships/americas/new-analyst-program',
    source_url: 'https://www.goldmansachs.com/careers/students/programs-and-internships/americas/',
    licenses_required: ['None Required'],
    licenses_info: null,
  },

  // ── J.P. Morgan ──
  {
    company_id: 'a1b2c3d4-0002-4000-8000-000000000002',
    title: 'Risk Management Analyst Program',
    category: 'Risk Management',
    location: 'New York, NY / Columbus, OH',
    remote_type: 'Hybrid',
    salary_min: 80000,
    salary_max: 95000,
    job_type: 'Full-time',
    pipeline_stage: 'New Grad',
    description: 'Join J.P. Morgan\'s Risk Management team as a full-time analyst. Work across market risk, credit risk, or operational risk functions supporting the firm\'s trading and lending activities. Build quantitative models, analyze portfolio exposures, and contribute to risk reporting for senior management and regulators.',
    apply_url: 'https://jpmc.fa.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1001/requisitions',
    source_url: 'https://careers.jpmorgan.com',
    licenses_required: ['None Required'],
    licenses_info: null,
  },

  // ── Charles Schwab ──
  {
    company_id: 'c0000000-0000-4000-8000-000000000022',
    title: 'Financial Services Representative',
    category: 'Financial Planning',
    location: 'Multiple US Locations',
    remote_type: 'Hybrid',
    salary_min: 48000,
    salary_max: 60000,
    job_type: 'Full-time',
    pipeline_stage: 'No Experience Required',
    description: 'Help Schwab clients manage their investments as a Financial Services Representative. Provide licensed guidance on brokerage accounts, retirement planning, and investment products. No prior finance experience needed. Schwab provides comprehensive training, licensing support, and a clear career path to Financial Consultant.',
    apply_url: 'https://www.schwabjobs.com/search-jobs',
    source_url: 'https://www.schwabjobs.com/search-jobs',
    licenses_required: ['SIE', 'Series 7', 'Series 63'],
    licenses_info: { study_time_days: 90, pass_deadline_days: 150, max_attempts: 3, prep_materials_paid: true, notes: 'Full licensing support during paid training program' },
  },

  // ── Northern Trust ──
  {
    company_id: 'c0000000-0000-4000-8000-000000000025',
    title: 'Wealth Management Analyst',
    category: 'Private Wealth',
    location: 'Chicago, IL',
    remote_type: 'Hybrid',
    salary_min: 65000,
    salary_max: 78000,
    job_type: 'Full-time',
    pipeline_stage: 'New Grad',
    description: 'Join Northern Trust\'s Wealth Management team serving ultra-high-net-worth clients and families. Support senior relationship managers with portfolio analysis, financial planning, trust administration, and client reporting. Two-year rotational program with exposure to investments, trust, and private banking.',
    apply_url: 'https://www.northerntrust.com/united-states/about-us/careers/students-and-graduates',
    source_url: 'https://www.northerntrust.com/united-states/about-us/careers/students-and-graduates',
    licenses_required: ['None Required'],
    licenses_info: null,
  },

  // ── BNY Mellon ──
  {
    company_id: 'c0000000-0000-4000-8000-000000000026',
    title: 'Asset Servicing Operations Analyst',
    category: 'Operations',
    location: 'Pittsburgh, PA / Lake Mary, FL',
    remote_type: 'Hybrid',
    salary_min: 55000,
    salary_max: 68000,
    job_type: 'Full-time',
    pipeline_stage: 'New Grad',
    description: 'Support BNY Mellon\'s Asset Servicing business by processing trades, managing corporate actions, and ensuring accurate custody operations for institutional clients. Learn the mechanics of global financial markets and securities processing. Structured analyst program with training and mentorship.',
    apply_url: 'https://www.bny.com/corporate/global/en/about-us/careers/students.html',
    source_url: 'https://www.bny.com/corporate/global/en/about-us/careers/students.html',
    licenses_required: ['None Required'],
    licenses_info: null,
  },

  // ── State Street ──
  {
    company_id: 'c0000000-0000-4000-8000-000000000027',
    title: 'Fund Accounting Analyst',
    category: 'Accounting',
    location: 'Boston, MA / Kansas City, MO',
    remote_type: 'Hybrid',
    salary_min: 55000,
    salary_max: 67000,
    job_type: 'Full-time',
    pipeline_stage: 'New Grad',
    description: 'Perform daily NAV calculations, reconciliations, and financial reporting for mutual funds and ETFs. Work with portfolio accounting systems to ensure accurate pricing and compliance. Learn the operational backbone of the asset management industry at one of the world\'s largest custodian banks.',
    apply_url: 'https://careers.statestreet.com',
    source_url: 'https://careers.statestreet.com',
    licenses_required: ['None Required'],
    licenses_info: null,
  },

  // ── T. Rowe Price ──
  {
    company_id: 'c0000000-0000-4000-8000-000000000024',
    title: 'Investment Associate - Global Equities',
    category: 'Research',
    location: 'Baltimore, MD',
    remote_type: 'Hybrid',
    salary_min: 75000,
    salary_max: 90000,
    job_type: 'Full-time',
    pipeline_stage: 'New Grad',
    description: 'Support T. Rowe Price\'s equity research effort by conducting fundamental analysis on public companies. Build financial models, attend management meetings, and contribute to investment recommendations. Work alongside experienced analysts and portfolio managers managing $1.4 trillion in assets.',
    apply_url: 'https://troweprice.wd5.myworkdayjobs.com/en-US/TRowePrice',
    source_url: 'https://troweprice.wd5.myworkdayjobs.com/en-US/TRowePrice',
    licenses_required: ['CFA Level 1'],
    licenses_info: { study_time_days: null, pass_deadline_days: null, max_attempts: null, prep_materials_paid: true, notes: 'CFA program encouraged; firm reimburses exam fees and provides study materials' },
  },

  // ── Deloitte ──
  {
    company_id: 'a1b2c3d4-0004-4000-8000-000000000004',
    title: 'Risk & Financial Advisory Analyst',
    category: 'Risk Management',
    location: 'Multiple US Locations',
    remote_type: 'Hybrid',
    salary_min: 72000,
    salary_max: 85000,
    job_type: 'Full-time',
    pipeline_stage: 'New Grad',
    description: 'Join Deloitte\'s Risk & Financial Advisory practice supporting clients with risk management, regulatory compliance, and internal controls. Work on engagements spanning financial services, technology, and healthcare sectors. Structured career path with training, mentorship, and CPA/certification support.',
    apply_url: 'https://apply.deloitte.com/en_US/careers/SearchJobs',
    source_url: 'https://apply.deloitte.com/en_US/careers/SearchJobs',
    licenses_required: ['None Required'],
    licenses_info: null,
  },

  // ── PwC ──
  {
    company_id: 'a1b2c3d4-0005-4000-8000-000000000005',
    title: 'Deals - Financial Due Diligence Associate',
    category: 'Consulting',
    location: 'New York, NY / Chicago, IL / Boston, MA',
    remote_type: 'Hybrid',
    salary_min: 80000,
    salary_max: 95000,
    job_type: 'Full-time',
    pipeline_stage: 'New Grad',
    description: 'Support PwC\'s Deals practice performing buy-side and sell-side financial due diligence for M&A transactions. Analyze financial statements, assess quality of earnings, identify deal risks, and present findings to private equity and corporate clients. Strong path to a career in transaction advisory or private equity.',
    apply_url: 'https://jobs.us.pwc.com/entry-level',
    source_url: 'https://jobs.us.pwc.com/entry-level',
    licenses_required: ['CPA Track'],
    licenses_info: { study_time_days: 180, pass_deadline_days: 540, max_attempts: null, prep_materials_paid: true, notes: 'PwC covers CPA exam costs and provides Becker study materials' },
  },

  // ── KPMG ──
  {
    company_id: 'f1ff85d8-5c24-41b2-b78e-9a2243d61a15',
    title: 'Deal Advisory Associate - Valuation',
    category: 'Corporate Finance',
    location: 'New York, NY / Chicago, IL',
    remote_type: 'Hybrid',
    salary_min: 78000,
    salary_max: 92000,
    job_type: 'Full-time',
    pipeline_stage: 'New Grad',
    description: 'Join KPMG\'s Deal Advisory practice performing business valuations for M&A transactions, financial reporting, tax compliance, and litigation. Build DCF models, analyze comparable companies, and present valuation conclusions to clients. Ideal for candidates interested in corporate finance and transaction advisory.',
    apply_url: 'https://www.kpmguscareers.com/early-career/',
    source_url: 'https://www.kpmguscareers.com/early-career/',
    licenses_required: ['CPA Track'],
    licenses_info: { study_time_days: 180, pass_deadline_days: 540, max_attempts: null, prep_materials_paid: true, notes: 'KPMG covers CPA exam costs and provides study materials' },
  },

  // ── RBC Capital Markets ──
  {
    company_id: 'e845a6f7-d4ca-4cf0-a5d0-b4ef0ec8aabe',
    title: 'Equity Research Associate',
    category: 'Research',
    location: 'New York, NY',
    remote_type: 'On-site',
    salary_min: 85000,
    salary_max: 100000,
    job_type: 'Full-time',
    pipeline_stage: 'New Grad',
    description: 'Support RBC Capital Markets\' equity research analysts covering specific industry sectors. Build financial models, write research reports, and analyze industry trends. Develop expertise in public equity valuation and communicate insights to institutional investor clients.',
    apply_url: 'https://www.rbccm.com/en/careers/full-time.page',
    source_url: 'https://www.rbccm.com/en/careers/full-time.page',
    licenses_required: ['SIE', 'Series 7', 'Series 63'],
    licenses_info: { study_time_days: 90, pass_deadline_days: 150, max_attempts: 3, prep_materials_paid: true, notes: 'RBC sponsors all FINRA licensing exams during onboarding' },
  },

  // ── Bridgewater Associates ──
  {
    company_id: '73852365-d123-43fc-8370-dc2aa7376ee9',
    title: 'Investment Logic Engineer',
    category: 'Research',
    location: 'Westport, CT',
    remote_type: 'On-site',
    salary_min: 100000,
    salary_max: 125000,
    job_type: 'Full-time',
    pipeline_stage: 'New Grad',
    description: 'Translate economic and market research into systematic trading strategies at Bridgewater Associates, the world\'s largest hedge fund. Work at the intersection of economics, data science, and software engineering to build and refine Bridgewater\'s investment system. Strong quantitative and programming skills required.',
    apply_url: 'https://www.bridgewater.com/careers',
    source_url: 'https://www.bridgewater.com/careers',
    licenses_required: ['None Required'],
    licenses_info: null,
  },

  // ── Houlihan Lokey ──
  {
    company_id: '69ce4f41-0bac-4cbf-8499-c270a18c590b',
    title: 'Restructuring Analyst',
    category: 'Investment Banking',
    location: 'New York, NY / Los Angeles, CA',
    remote_type: 'On-site',
    salary_min: 105000,
    salary_max: 115000,
    job_type: 'Full-time',
    pipeline_stage: 'New Grad',
    description: 'Join Houlihan Lokey\'s #1-ranked restructuring practice as a full-time analyst. Advise companies and creditors navigating financial distress through out-of-court workouts, Chapter 11 bankruptcies, and liability management exercises. Build complex financial models and contribute to client presentations and court filings.',
    apply_url: 'https://hl.wd1.myworkdayjobs.com/Campus',
    source_url: 'https://hl.wd1.myworkdayjobs.com/Campus',
    licenses_required: ['None Required'],
    licenses_info: null,
  },

  // ── Grant Thornton ──
  {
    company_id: '831fbc67-f19e-4121-b8b6-f068237ee171',
    title: 'Audit Associate - Financial Services',
    category: 'Accounting',
    location: 'Chicago, IL / New York, NY',
    remote_type: 'Hybrid',
    salary_min: 62000,
    salary_max: 75000,
    job_type: 'Full-time',
    pipeline_stage: 'New Grad',
    description: 'Join Grant Thornton\'s Audit practice as an Associate serving financial services clients including banks, insurance companies, and asset managers. Perform audit procedures, test internal controls, and prepare financial statement work papers. CPA eligibility required; firm provides full exam support.',
    apply_url: 'https://www.grantthornton.com/careers',
    source_url: 'https://www.grantthornton.com/careers',
    licenses_required: ['CPA Track'],
    licenses_info: { study_time_days: 180, pass_deadline_days: 540, max_attempts: null, prep_materials_paid: true, notes: 'GT covers CPA exam fees and provides Becker study materials' },
  },
]

export async function POST() {
  try {
    // 1. Insert new companies
    let companiesAdded = 0
    for (const company of newCompanies) {
      const { error } = await supabaseAdmin
        .from('companies')
        .upsert(company, { onConflict: 'id' })
      if (!error) companiesAdded++
    }

    // 2. Insert new jobs
    let jobsAdded = 0
    let jobErrors: string[] = []
    const now = new Date().toISOString()

    for (const job of newJobs) {
      const jobRecord = {
        id: randomUUID(),
        ...job,
        is_active: true,
        is_verified: true,
        posted_date: now,
        last_verified_at: now,
        removal_detected_at: null,
        verification_count: 1,
        created_at: now,
        updated_at: now,
        grad_date_required: (job as any).grad_date_required || false,
        grad_date_earliest: (job as any).grad_date_earliest || null,
        grad_date_latest: (job as any).grad_date_latest || null,
        years_experience_max: null,
      }
      const { error } = await supabaseAdmin.from('jobs').insert(jobRecord)
      if (error) {
        jobErrors.push(`${job.title}: ${error.message}`)
      } else {
        jobsAdded++
      }
    }

    return NextResponse.json({
      success: true,
      companiesAdded,
      jobsAdded,
      jobErrors: jobErrors.length > 0 ? jobErrors : undefined,
      totalNewJobs: newJobs.length,
    })
  } catch (err: any) {
    return NextResponse.json({ error: err.message }, { status: 500 })
  }
}
