import { NextResponse } from 'next/server'
import { supabaseAdmin } from '@/lib/supabaseAdmin'

export async function POST() {
  try {
    // New companies to add
    const newCompanies = [
      {
        name: 'Lazard',
        website: 'https://www.lazard.com',
        careers_url: 'https://www.lazard.com/careers/',
        description: 'Global financial advisory and asset management firm advising on mergers, acquisitions, restructuring, and capital raising.',
      },
      {
        name: 'Jefferies',
        website: 'https://www.jefferies.com',
        careers_url: 'https://www.jefferies.com/careers',
        description: 'Full-service investment banking and capital markets firm providing advisory, sales, trading, and research services.',
      },
      {
        name: 'Moelis & Company',
        website: 'https://www.moelis.com',
        careers_url: 'https://www.moelis.com/careers',
        description: 'Independent investment bank providing strategic advice on mergers, recapitalizations, restructurings, and other complex transactions.',
      },
      {
        name: 'Evercore',
        website: 'https://www.evercore.com',
        careers_url: 'https://www.evercore.com/careers/',
        description: 'Premier independent investment banking advisory firm focused on advisory, including mergers and acquisitions and strategic advisory.',
      },
      {
        name: 'Raymond James',
        website: 'https://www.raymondjames.com',
        careers_url: 'https://www.raymondjames.com/careers',
        description: 'Diversified financial services holding company providing private client group, capital markets, asset management, and banking services.',
      },
      {
        name: 'William Blair',
        website: 'https://www.williamblair.com',
        careers_url: 'https://www.williamblair.com/Careers',
        description: 'Global investment banking and asset management firm offering research, brokerage, and private capital services.',
      },
    ]

    // Insert new companies
    const companyIds: Record<string, string> = {}
    for (const co of newCompanies) {
      const { data: existing } = await supabaseAdmin
        .from('companies')
        .select('id')
        .eq('name', co.name)
        .single()

      if (existing) {
        companyIds[co.name] = existing.id
      } else {
        const { data: inserted } = await supabaseAdmin
          .from('companies')
          .insert(co)
          .select('id')
          .single()
        if (inserted) companyIds[co.name] = inserted.id
      }
    }

    // Get existing company IDs
    const existingCompanies = ['J.P. Morgan', 'Goldman Sachs', 'Morgan Stanley', 'Bank of America', 'Citi', 'Deloitte', 'PwC', 'KPMG', 'EY', 'Wells Fargo', 'Charles Schwab', 'Fidelity Investments', 'Northern Trust', 'BNY Mellon', 'State Street']
    for (const name of existingCompanies) {
      const { data } = await supabaseAdmin
        .from('companies')
        .select('id')
        .eq('name', name)
        .single()
      if (data) companyIds[name] = data.id
    }

    const now = new Date().toISOString()
    const daysAgo = (d: number) => new Date(Date.now() - d * 86400000).toISOString().split('T')[0]

    const jobs = [
      // J.P. Morgan Summer Analyst Programs
      {
        company_id: companyIds['J.P. Morgan'],
        title: '2027 Markets Summer Analyst Program - Research',
        category: 'Research',
        location: 'New York, NY',
        remote_type: 'On-site',
        salary_min: 95000,
        salary_max: 110000,
        job_type: 'Internship',
        pipeline_stage: 'Junior Internship',
        description: 'Gain hands-on experience in global markets research at J.P. Morgan. Spend your time exploring the sophisticated financial solutions we deliver across asset classes. Expected graduation 2028.',
        apply_url: 'https://jpmc.fa.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1001/jobs',
        source_url: 'https://jpmc.fa.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1001/jobs',
        licenses_required: ['None Required'],
        posted_date: daysAgo(2),
        grad_date_required: true,
        grad_date_earliest: '2027-12-01',
        grad_date_latest: '2028-06-30',
      },
      {
        company_id: companyIds['J.P. Morgan'],
        title: '2027 Markets Summer Analyst Program',
        category: 'Sales & Trading',
        location: 'New York, NY',
        remote_type: 'On-site',
        salary_min: 95000,
        salary_max: 110000,
        job_type: 'Internship',
        pipeline_stage: 'Junior Internship',
        description: 'Gain hands-on experience in global markets supporting Research, Sales, Trading, Structuring & Origination, or Digital Markets. Expected graduation 2028.',
        apply_url: 'https://jpmc.fa.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1001/jobs',
        source_url: 'https://jpmc.fa.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1001/jobs',
        licenses_required: ['None Required'],
        posted_date: daysAgo(2),
        grad_date_required: true,
        grad_date_earliest: '2027-12-01',
        grad_date_latest: '2028-06-30',
      },
      {
        company_id: companyIds['J.P. Morgan'],
        title: '2027 Commercial Real Estate Summer Analyst Program',
        category: 'Corporate Finance',
        location: 'Atlanta, GA',
        remote_type: 'On-site',
        salary_min: 85000,
        salary_max: 100000,
        job_type: 'Internship',
        pipeline_stage: 'Junior Internship',
        description: '2027 Commercial Real Estate Summer Analyst Program at J.P. Morgan. Work on real estate transactions and portfolio management.',
        apply_url: 'https://jpmc.fa.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1001/jobs',
        source_url: 'https://jpmc.fa.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1001/jobs',
        licenses_required: ['None Required'],
        posted_date: daysAgo(3),
        grad_date_required: true,
        grad_date_earliest: '2027-12-01',
        grad_date_latest: '2028-06-30',
      },
      {
        company_id: companyIds['J.P. Morgan'],
        title: '2027 Global Corporate Banking Summer Analyst Program',
        category: 'Commercial Banking',
        location: 'New York, NY',
        remote_type: 'On-site',
        salary_min: 95000,
        salary_max: 110000,
        job_type: 'Internship',
        pipeline_stage: 'Junior Internship',
        description: 'Spend your summer working with our industry experts to deliver the full power of the firm to help clients grow their business. Global Corporate Banking Summer Analyst Program.',
        apply_url: 'https://jpmc.fa.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1001/jobs',
        source_url: 'https://jpmc.fa.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1001/jobs',
        licenses_required: ['None Required'],
        posted_date: daysAgo(3),
        grad_date_required: true,
        grad_date_earliest: '2027-12-01',
        grad_date_latest: '2028-06-30',
      },
      {
        company_id: companyIds['J.P. Morgan'],
        title: '2027 Public Finance Banking Summer Analyst Program',
        category: 'Investment Banking',
        location: 'New York, NY',
        remote_type: 'On-site',
        salary_min: 95000,
        salary_max: 110000,
        job_type: 'Internship',
        pipeline_stage: 'Junior Internship',
        description: '2027 Public Finance Banking Analyst Internship at J.P. Morgan. Focus on municipal finance and public sector advisory.',
        apply_url: 'https://jpmc.fa.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1001/jobs',
        source_url: 'https://jpmc.fa.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1001/jobs',
        licenses_required: ['None Required'],
        posted_date: daysAgo(4),
        grad_date_required: true,
        grad_date_earliest: '2027-12-01',
        grad_date_latest: '2028-06-30',
      },
      {
        company_id: companyIds['J.P. Morgan'],
        title: '2027 Asset Management Client Analyst Summer Program',
        category: 'Private Wealth',
        location: 'New York, NY',
        remote_type: 'On-site',
        salary_min: 85000,
        salary_max: 100000,
        job_type: 'Internship',
        pipeline_stage: 'Junior Internship',
        description: 'Asset Management Client Analyst Training Program working to develop investment strategies for clients. Expected graduation 2028.',
        apply_url: 'https://jpmc.fa.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1001/jobs',
        source_url: 'https://jpmc.fa.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1001/jobs',
        licenses_required: ['None Required'],
        posted_date: daysAgo(3),
        grad_date_required: true,
        grad_date_earliest: '2027-12-01',
        grad_date_latest: '2028-06-30',
      },
      {
        company_id: companyIds['J.P. Morgan'],
        title: '2027 Asset Management Product Summer Analyst Program',
        category: 'Private Wealth',
        location: 'New York, NY',
        remote_type: 'On-site',
        salary_min: 85000,
        salary_max: 100000,
        job_type: 'Internship',
        pipeline_stage: 'Junior Internship',
        description: 'Asset Management Product Analyst Training Program working to develop investment strategies for clients. Expected graduation 2028.',
        apply_url: 'https://jpmc.fa.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1001/jobs',
        source_url: 'https://jpmc.fa.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1001/jobs',
        licenses_required: ['None Required'],
        posted_date: daysAgo(4),
        grad_date_required: true,
        grad_date_earliest: '2027-12-01',
        grad_date_latest: '2028-06-30',
      },
      {
        company_id: companyIds['J.P. Morgan'],
        title: '2027 Asset & Wealth Management Risk Summer Analyst Program',
        category: 'Risk Management',
        location: 'Columbus, OH',
        remote_type: 'On-site',
        salary_min: 80000,
        salary_max: 95000,
        job_type: 'Internship',
        pipeline_stage: 'Junior Internship',
        description: 'Risk Analyst Training Program to help clients achieve financial objectives through risk management. Expected graduation 2028.',
        apply_url: 'https://jpmc.fa.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1001/jobs',
        source_url: 'https://jpmc.fa.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1001/jobs',
        licenses_required: ['None Required'],
        posted_date: daysAgo(5),
        grad_date_required: true,
        grad_date_earliest: '2027-12-01',
        grad_date_latest: '2028-06-30',
      },
      {
        company_id: companyIds['J.P. Morgan'],
        title: 'Emerging Talent - Process Improvement Associate',
        category: 'Operations',
        location: 'Columbus, OH',
        remote_type: 'Hybrid',
        salary_min: 65000,
        salary_max: 80000,
        job_type: 'Full-time',
        pipeline_stage: 'New Grad',
        description: 'Drive business transformation and excellence via process review, data analysis, project management, and innovative solutions. Graduating student opportunity.',
        apply_url: 'https://jpmc.fa.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1001/jobs',
        source_url: 'https://jpmc.fa.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1001/jobs',
        licenses_required: ['None Required'],
        posted_date: daysAgo(1),
        grad_date_required: true,
        grad_date_earliest: '2025-12-01',
        grad_date_latest: '2026-06-30',
      },
      {
        company_id: companyIds['J.P. Morgan'],
        title: '2027 Latin America Debt Capital Markets Summer Analyst',
        category: 'Investment Banking',
        location: 'New York, NY',
        remote_type: 'On-site',
        salary_min: 95000,
        salary_max: 110000,
        job_type: 'Internship',
        pipeline_stage: 'Junior Internship',
        description: 'Latin America Debt Capital Markets Summer Analyst program. Work on debt financing transactions across Latin American markets.',
        apply_url: 'https://jpmc.fa.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1001/jobs',
        source_url: 'https://jpmc.fa.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1001/jobs',
        licenses_required: ['None Required'],
        posted_date: daysAgo(5),
        grad_date_required: true,
        grad_date_earliest: '2027-12-01',
        grad_date_latest: '2028-06-30',
      },
      // Goldman Sachs
      {
        company_id: companyIds['Goldman Sachs'],
        title: 'Wealth Management Ayco Analyst',
        category: 'Private Wealth',
        location: 'Dallas, TX',
        remote_type: 'Hybrid',
        salary_min: 70000,
        salary_max: 85000,
        job_type: 'Full-time',
        pipeline_stage: 'New Grad',
        description: 'Join Goldman Sachs Ayco Personal Financial Management as a Wealth Management Analyst. Provide financial planning and wealth management services to corporate executives.',
        apply_url: 'https://higher.gs.com/roles',
        source_url: 'https://higher.gs.com/roles',
        licenses_required: ['SIE', 'Series 7', 'Series 66'],
        posted_date: daysAgo(1),
      },
      {
        company_id: companyIds['Goldman Sachs'],
        title: 'Wealth Management Ayco Analyst',
        category: 'Private Wealth',
        location: 'Troy, MI',
        remote_type: 'Hybrid',
        salary_min: 70000,
        salary_max: 85000,
        job_type: 'Full-time',
        pipeline_stage: 'New Grad',
        description: 'Join Goldman Sachs Ayco Personal Financial Management as a Wealth Management Analyst in Troy/Detroit. Provide financial planning and wealth management services.',
        apply_url: 'https://higher.gs.com/roles',
        source_url: 'https://higher.gs.com/roles',
        licenses_required: ['SIE', 'Series 7', 'Series 66'],
        posted_date: daysAgo(2),
      },
      {
        company_id: companyIds['Goldman Sachs'],
        title: 'Global Investment Research Associate - Equity Research',
        category: 'Research',
        location: 'New York, NY',
        remote_type: 'On-site',
        salary_min: 110000,
        salary_max: 135000,
        job_type: 'Full-time',
        pipeline_stage: 'New Grad',
        description: 'Join Global Investment Research at Goldman Sachs covering Equity Research in Payments & Fintech. Analyze companies, build financial models, and publish research.',
        apply_url: 'https://higher.gs.com/roles',
        source_url: 'https://higher.gs.com/roles',
        licenses_required: ['None Required'],
        posted_date: daysAgo(3),
      },
      {
        company_id: companyIds['Goldman Sachs'],
        title: 'Global Banking & Markets - Industrials Sales Analyst',
        category: 'Sales & Trading',
        location: 'New York, NY',
        remote_type: 'On-site',
        salary_min: 100000,
        salary_max: 120000,
        job_type: 'Full-time',
        pipeline_stage: 'New Grad',
        description: 'Join the Industrials Sales desk at Goldman Sachs. Cover institutional clients and provide market insights across industrials sector equities.',
        apply_url: 'https://higher.gs.com/roles',
        source_url: 'https://higher.gs.com/roles',
        licenses_required: ['SIE', 'Series 7', 'Series 63'],
        posted_date: daysAgo(2),
      },
      {
        company_id: companyIds['Goldman Sachs'],
        title: 'Asset & Wealth Management - Financial Planning Associate',
        category: 'Financial Planning',
        location: 'New York, NY',
        remote_type: 'Hybrid',
        salary_min: 85000,
        salary_max: 100000,
        job_type: 'Full-time',
        pipeline_stage: 'New Grad',
        description: 'Join the Goldman Partner Office Financial Planning team within Asset & Wealth Management. Provide comprehensive financial planning services.',
        apply_url: 'https://higher.gs.com/roles',
        source_url: 'https://higher.gs.com/roles',
        licenses_required: ['None Required'],
        posted_date: daysAgo(4),
      },
      // Lazard
      {
        company_id: companyIds['Lazard'],
        title: 'Financial Advisory Analyst',
        category: 'Investment Banking',
        location: 'New York, NY',
        remote_type: 'On-site',
        salary_min: 110000,
        salary_max: 130000,
        job_type: 'Full-time',
        pipeline_stage: 'New Grad',
        description: 'Join Lazard as a Financial Advisory Analyst working on M&A, restructuring, and capital raising transactions for leading corporations worldwide.',
        apply_url: 'https://www.lazard.com/careers/',
        source_url: 'https://www.lazard.com/careers/',
        licenses_required: ['None Required'],
        posted_date: daysAgo(6),
      },
      {
        company_id: companyIds['Lazard'],
        title: 'Asset Management Summer Analyst',
        category: 'Private Wealth',
        location: 'New York, NY',
        remote_type: 'On-site',
        salary_min: 95000,
        salary_max: 110000,
        job_type: 'Internship',
        pipeline_stage: 'Junior Internship',
        description: 'Summer analyst program within Lazard Asset Management. Gain exposure to equity research, portfolio management, and client advisory.',
        apply_url: 'https://www.lazard.com/careers/',
        source_url: 'https://www.lazard.com/careers/',
        licenses_required: ['None Required'],
        posted_date: daysAgo(8),
      },
      // Jefferies
      {
        company_id: companyIds['Jefferies'],
        title: 'Investment Banking Analyst - Healthcare',
        category: 'Investment Banking',
        location: 'New York, NY',
        remote_type: 'On-site',
        salary_min: 110000,
        salary_max: 130000,
        job_type: 'Full-time',
        pipeline_stage: 'New Grad',
        description: 'Join the Healthcare Investment Banking team at Jefferies. Work on M&A, equity, and debt transactions for healthcare companies.',
        apply_url: 'https://www.jefferies.com/careers',
        source_url: 'https://www.jefferies.com/careers',
        licenses_required: ['None Required'],
        posted_date: daysAgo(5),
      },
      {
        company_id: companyIds['Jefferies'],
        title: 'Equity Research Associate - Technology',
        category: 'Research',
        location: 'New York, NY',
        remote_type: 'On-site',
        salary_min: 95000,
        salary_max: 115000,
        job_type: 'Full-time',
        pipeline_stage: 'New Grad',
        description: 'Join Jefferies Equity Research covering the technology sector. Build financial models, publish research, and engage with institutional investors.',
        apply_url: 'https://www.jefferies.com/careers',
        source_url: 'https://www.jefferies.com/careers',
        licenses_required: ['None Required'],
        posted_date: daysAgo(7),
      },
      // Moelis
      {
        company_id: companyIds['Moelis & Company'],
        title: 'Investment Banking Analyst',
        category: 'Investment Banking',
        location: 'New York, NY',
        remote_type: 'On-site',
        salary_min: 110000,
        salary_max: 130000,
        job_type: 'Full-time',
        pipeline_stage: 'New Grad',
        description: 'Join Moelis & Company as an Investment Banking Analyst. Work on complex M&A, restructuring, and recapitalization transactions.',
        apply_url: 'https://www.moelis.com/careers',
        source_url: 'https://www.moelis.com/careers',
        licenses_required: ['None Required'],
        posted_date: daysAgo(4),
      },
      // Evercore
      {
        company_id: companyIds['Evercore'],
        title: 'Advisory Analyst',
        category: 'Investment Banking',
        location: 'New York, NY',
        remote_type: 'On-site',
        salary_min: 110000,
        salary_max: 135000,
        job_type: 'Full-time',
        pipeline_stage: 'New Grad',
        description: 'Join Evercore as an Advisory Analyst working on mergers and acquisitions, strategic advisory, and capital advisory transactions.',
        apply_url: 'https://www.evercore.com/careers/',
        source_url: 'https://www.evercore.com/careers/',
        licenses_required: ['None Required'],
        posted_date: daysAgo(6),
      },
      {
        company_id: companyIds['Evercore'],
        title: 'Summer Advisory Intern',
        category: 'Investment Banking',
        location: 'New York, NY',
        remote_type: 'On-site',
        salary_min: 95000,
        salary_max: 110000,
        job_type: 'Internship',
        pipeline_stage: 'Junior Internship',
        description: 'Summer internship in Evercore Advisory. Gain hands-on experience in M&A advisory and strategic consulting.',
        apply_url: 'https://www.evercore.com/careers/',
        source_url: 'https://www.evercore.com/careers/',
        licenses_required: ['None Required'],
        posted_date: daysAgo(10),
      },
      // Raymond James
      {
        company_id: companyIds['Raymond James'],
        title: 'Financial Advisor Associate',
        category: 'Financial Planning',
        location: 'St. Petersburg, FL',
        remote_type: 'On-site',
        salary_min: 60000,
        salary_max: 75000,
        job_type: 'Full-time',
        pipeline_stage: 'No Experience Required',
        description: 'Begin your career as a Financial Advisor Associate at Raymond James. Complete training program and work toward building your own advisory practice.',
        apply_url: 'https://www.raymondjames.com/careers',
        source_url: 'https://www.raymondjames.com/careers',
        licenses_required: ['SIE', 'Series 7', 'Series 66'],
        posted_date: daysAgo(3),
      },
      {
        company_id: companyIds['Raymond James'],
        title: 'Investment Banking Summer Analyst',
        category: 'Investment Banking',
        location: 'New York, NY',
        remote_type: 'On-site',
        salary_min: 85000,
        salary_max: 100000,
        job_type: 'Internship',
        pipeline_stage: 'Junior Internship',
        description: 'Summer analyst position in Raymond James Investment Banking division. Work on M&A, capital markets, and restructuring transactions.',
        apply_url: 'https://www.raymondjames.com/careers',
        source_url: 'https://www.raymondjames.com/careers',
        licenses_required: ['None Required'],
        posted_date: daysAgo(7),
      },
      // William Blair
      {
        company_id: companyIds['William Blair'],
        title: 'Investment Banking Analyst',
        category: 'Investment Banking',
        location: 'Chicago, IL',
        remote_type: 'On-site',
        salary_min: 100000,
        salary_max: 120000,
        job_type: 'Full-time',
        pipeline_stage: 'New Grad',
        description: 'Join William Blair as an Investment Banking Analyst in Chicago. Work on M&A advisory and capital markets transactions across multiple industry verticals.',
        apply_url: 'https://www.williamblair.com/Careers',
        source_url: 'https://www.williamblair.com/Careers',
        licenses_required: ['None Required'],
        posted_date: daysAgo(5),
      },
      {
        company_id: companyIds['William Blair'],
        title: 'Equity Research Associate',
        category: 'Research',
        location: 'Chicago, IL',
        remote_type: 'Hybrid',
        salary_min: 80000,
        salary_max: 100000,
        job_type: 'Full-time',
        pipeline_stage: 'New Grad',
        description: 'Join the Equity Research team at William Blair. Support senior analysts with financial modeling, industry research, and client engagement.',
        apply_url: 'https://www.williamblair.com/Careers',
        source_url: 'https://www.williamblair.com/Careers',
        licenses_required: ['None Required'],
        posted_date: daysAgo(8),
      },
      // Additional roles at existing companies
      {
        company_id: companyIds['Morgan Stanley'],
        title: 'Wealth Management Associate',
        category: 'Private Wealth',
        location: 'New York, NY',
        remote_type: 'On-site',
        salary_min: 75000,
        salary_max: 90000,
        job_type: 'Full-time',
        pipeline_stage: 'New Grad',
        description: 'Join Morgan Stanley Wealth Management as an Associate. Support Financial Advisors in managing client portfolios and delivering investment solutions.',
        apply_url: 'https://www.morganstanley.com/careers',
        source_url: 'https://www.morganstanley.com/careers',
        licenses_required: ['SIE', 'Series 7', 'Series 66'],
        posted_date: daysAgo(2),
      },
      {
        company_id: companyIds['Citi'],
        title: 'Investment Banking Analyst - TMT',
        category: 'Investment Banking',
        location: 'New York, NY',
        remote_type: 'On-site',
        salary_min: 110000,
        salary_max: 130000,
        job_type: 'Full-time',
        pipeline_stage: 'New Grad',
        description: 'Join Citi Investment Banking as a TMT (Technology, Media & Telecommunications) Analyst. Work on M&A advisory, debt and equity offerings.',
        apply_url: 'https://jobs.citi.com',
        source_url: 'https://jobs.citi.com',
        licenses_required: ['None Required'],
        posted_date: daysAgo(3),
      },
      {
        company_id: companyIds['Bank of America'],
        title: 'Global Markets Sales & Trading Analyst',
        category: 'Sales & Trading',
        location: 'New York, NY',
        remote_type: 'On-site',
        salary_min: 95000,
        salary_max: 115000,
        job_type: 'Full-time',
        pipeline_stage: 'New Grad',
        description: 'Join Bank of America Global Markets as a Sales & Trading Analyst. Rotate across equity and fixed income desks.',
        apply_url: 'https://careers.bankofamerica.com',
        source_url: 'https://careers.bankofamerica.com',
        licenses_required: ['SIE', 'Series 7', 'Series 63'],
        posted_date: daysAgo(4),
      },
      {
        company_id: companyIds['Northern Trust'],
        title: 'Wealth Advisory Associate',
        category: 'Private Wealth',
        location: 'Chicago, IL',
        remote_type: 'Hybrid',
        salary_min: 65000,
        salary_max: 80000,
        job_type: 'Full-time',
        pipeline_stage: 'New Grad',
        description: 'Support wealth advisors in managing high-net-worth client relationships. Prepare financial plans, investment proposals, and portfolio reviews.',
        apply_url: 'https://www.northerntrust.com/careers',
        source_url: 'https://www.northerntrust.com/careers',
        licenses_required: ['None Required'],
        posted_date: daysAgo(6),
      },
      {
        company_id: companyIds['BNY Mellon'],
        title: 'Fund Accounting Analyst',
        category: 'Accounting',
        location: 'Pittsburgh, PA',
        remote_type: 'Hybrid',
        salary_min: 55000,
        salary_max: 68000,
        job_type: 'Full-time',
        pipeline_stage: 'No Experience Required',
        description: 'Perform daily NAV calculations, reconcile portfolio positions, and prepare financial statements for investment funds.',
        apply_url: 'https://www.bnymellon.com/careers',
        source_url: 'https://www.bnymellon.com/careers',
        licenses_required: ['None Required'],
        posted_date: daysAgo(5),
      },
      {
        company_id: companyIds['State Street'],
        title: 'Investment Operations Analyst',
        category: 'Operations',
        location: 'Boston, MA',
        remote_type: 'Hybrid',
        salary_min: 58000,
        salary_max: 72000,
        job_type: 'Full-time',
        pipeline_stage: 'No Experience Required',
        description: 'Support trade processing, settlement, and reconciliation for institutional investment portfolios. Entry-level operations role.',
        apply_url: 'https://careers.statestreet.com',
        source_url: 'https://careers.statestreet.com',
        licenses_required: ['None Required'],
        posted_date: daysAgo(4),
      },
      {
        company_id: companyIds['Deloitte'],
        title: 'Audit & Assurance Associate',
        category: 'Accounting',
        location: 'Chicago, IL',
        remote_type: 'Hybrid',
        salary_min: 68000,
        salary_max: 78000,
        job_type: 'Full-time',
        pipeline_stage: 'New Grad',
        description: 'Join Deloitte Audit & Assurance practice. Perform financial statement audits and attestation services for Fortune 500 clients.',
        apply_url: 'https://apply.deloitte.com',
        source_url: 'https://apply.deloitte.com',
        licenses_required: ['CPA Track'],
        posted_date: daysAgo(2),
      },
      {
        company_id: companyIds['EY'],
        title: 'Transaction Advisory Services Associate',
        category: 'Consulting',
        location: 'New York, NY',
        remote_type: 'Hybrid',
        salary_min: 72000,
        salary_max: 85000,
        job_type: 'Full-time',
        pipeline_stage: 'New Grad',
        description: 'Join EY Transaction Advisory Services. Provide due diligence, financial modeling, and strategic advice on M&A transactions.',
        apply_url: 'https://www.ey.com/en_us/careers',
        source_url: 'https://www.ey.com/en_us/careers',
        licenses_required: ['None Required'],
        posted_date: daysAgo(3),
      },
      {
        company_id: companyIds['Fidelity Investments'],
        title: 'Financial Representative',
        category: 'Financial Planning',
        location: 'Denver, CO',
        remote_type: 'Hybrid',
        salary_min: 55000,
        salary_max: 70000,
        job_type: 'Full-time',
        pipeline_stage: 'No Experience Required',
        description: 'Help Fidelity customers with investment guidance and financial planning. Entry-level role with comprehensive training and licensing support.',
        apply_url: 'https://jobs.fidelity.com',
        source_url: 'https://jobs.fidelity.com',
        licenses_required: ['SIE', 'Series 7', 'Series 63'],
        posted_date: daysAgo(1),
      },
      {
        company_id: companyIds['Charles Schwab'],
        title: 'Financial Consultant Trainee',
        category: 'Financial Planning',
        location: 'Austin, TX',
        remote_type: 'Hybrid',
        salary_min: 55000,
        salary_max: 68000,
        job_type: 'Full-time',
        pipeline_stage: 'No Experience Required',
        description: 'Begin your career in financial consulting at Schwab. Complete training program and earn licenses to serve individual investors.',
        apply_url: 'https://www.schwab.com/careers',
        source_url: 'https://www.schwab.com/careers',
        licenses_required: ['SIE', 'Series 7', 'Series 66'],
        posted_date: daysAgo(5),
      },
      {
        company_id: companyIds['Wells Fargo'],
        title: 'Commercial Banking Analyst Program',
        category: 'Commercial Banking',
        location: 'Charlotte, NC',
        remote_type: 'On-site',
        salary_min: 70000,
        salary_max: 82000,
        job_type: 'Full-time',
        pipeline_stage: 'New Grad',
        description: 'Two-year rotational analyst program in Wells Fargo Commercial Banking. Rotate through credit, relationship management, and portfolio management.',
        apply_url: 'https://www.wellsfargojobs.com',
        source_url: 'https://www.wellsfargojobs.com',
        licenses_required: ['None Required'],
        posted_date: daysAgo(7),
      },
    ].map(j => ({
      ...j,
      is_active: true,
      is_verified: true,
      last_verified_at: now,
      verification_count: 1,
      licenses_required: j.licenses_required || ['None Required'],
      grad_date_required: j.grad_date_required || false,
      grad_date_earliest: j.grad_date_earliest || null,
      grad_date_latest: j.grad_date_latest || null,
      years_experience_max: j.pipeline_stage.includes('Internship') ? 0 : j.pipeline_stage === 'New Grad' ? 1 : j.pipeline_stage === 'No Experience Required' ? 0 : 3,
    }))

    const { data: insertedJobs, error } = await supabaseAdmin
      .from('jobs')
      .insert(jobs)
      .select('id')

    if (error) throw error

    return NextResponse.json({
      success: true,
      companiesAdded: Object.keys(companyIds).length,
      jobsAdded: insertedJobs?.length || 0,
    })
  } catch (err: any) {
    return NextResponse.json({ error: err.message }, { status: 500 })
  }
}
